ARDUINO_DIR   = /Applications/Arduino.app/Contents/Resources/Java
ARDMK_DIR     = /usr/local/opt/arduino-mk
AVR_TOOLS_DIR = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr
AVRDUDE_CONF  = /Applications/Arduino.app/Contents/Resources/Java/hardware/tools/avr/etc/avrdude.conf
# MONITOR_PORT  = /dev/cu.usbserial-A9ORRL9X
BOARD_TAG	  = pro5v
MONITOR_PORT = /dev/tty.usbserial-FTDY80ON
# BOARD_TAG     = nano328

include /usr/local/opt/arduino-mk/Arduino.mk
